//
//  TDApiKey.swift
//  TourDe
//
//  Created by Tran Manh Quy on 4/4/18.
//  Copyright © 2018 Yume-sol. All rights reserved.
//

import Foundation

class TDApiKey {
    static let GET_COURSE_LIST = "/test/api/get/getCourseList/"
    static let GET_FAVORITE_COURSE_LIST = "/test/api/get/getFavoriteCourseListApp/"
    static let GET_DETAIL_COURSE = "/test/api/get/getCourseData/"
    static let GET_ACCOUNT_INFO = "/test/api/get/getAccount/"
    static let GET_RUN_COURSE_LIST = "/test/api/get/getRunCourseList/"
    static let POST_CREATE_ACCOUNT = "/test/api/post/createAccount/"
    static let POST_EDIT_ACCOUNT = "/test/api/post/editAccount/"
    static let POST_LOGIN_EMAIL = "/test/api/post/loginAccountEmail/"
    static let POST_LOGIN_SNS = "/test/api/post/loginAccountSNS/"
    static let POST_LOGOUT_ACCOUNT = "/test/api/post/logoutAccount/"
    static let POST_REVIEW_COURSE = "/test/api/post/reviewCourse/"
    static let POST_INSERT_FAVORITE_COURSE_APP = "/test/api/post/insertFavoriteCourseApp/"
    static let POST_DELETE_FAVORITE_COURSE_APP = "/test/api/post/deleteFavoriteCourseApp/"
    static let POST_CHECK_COURSE_REVIEW = "/test/api/post/checkCourseReview/"
    static let POST_RESET_PASSWORD = "/test/api/post/resetPassword/"
    static let POST_COURSE_LOG = "/test/api/post/postCourseLog/"
    static let POST_REVIEW_SPOT_EQUIPMENT = "/test/api/post/reviewSpotEquipment/"
    static let GET_SPOT_DATA = "/test/api/get/getSpotData/"
    static let GET_SPOT_EQUIPMENT_REVIEW = "/test/api/get/getSpotEquipmentReview/"
    static let GET_POSTED_SPOT_IMAGE_LIST = "/test/api/get/getPostedSpotImageList/"
    static let GET_MAINTENANCE_STATUS = "/test/api/get/getMaintenanceStatus/"
    static let POST_CHECK_APPLICATION_VERSION = "/test/api/post/checkApplicationVersion/"
    static let GET_CHECKED_STAMP_LIST = "/test/api/get/getCheckedStampList/"
    static let POST_CHECK_IN_STAMP = "/test/api/post/checkInStamp/"
    static let POST_COURSE_IMAGE = "/test/api/post/postCourseImage/"
    static let POST_SPOT_IMAGE = "/test/api/post/postSpotImage/"
    static let POST_IMAGE = "/test/api/post/postImage/"
    static let page = "page"
    static let limit = "limit"
    static let prefecture = "prefecture[]"
    static let distance_type = "distance_type"
    static let over_elevation = "over_elevation"
    static let less_elevation = "less_elevation"
    static let course_type = "course_type[]"
    static let freeword = "freeword"
    static let season = "season[]"
    static let tag = "tag[]"
    static let email = "email"
    static let password = "password"
    static let sex = "sex"
    static let age = "age"
    static let nickname = "nickname"
    static let sns_id = "sns_id"
    static let sns_kind = "sns_kind"
    static let course_id = "course_id"
    static let token = "token"
    static let rating = "rating"
    static let comment = "comment"
    static let image = "image"
    static let area = "area"
    static let spot_id = "spot_id"
    static let user_image_id = "user_image_id"
    static let speed_average = "speed_average"
    static let finish_time = "finish_time"
    static let toilet = "toilet"
    static let parking = "parking"
    static let accommodation = "accommodation"
    static let bath = "bath"
    static let shower = "shower"
    static let locker = "locker"
    static let dressing_room = "dressing_room"
    static let bicycle_delivery = "bicycle_delivery"
    static let tourist_information = "tourist_information"
    static let cycle_rack = "cycle_rack"
    static let bicycle_rental = "bicycle_rental"
    static let cycling_guide = "cycling_guide"
    static let tool_rental = "tool_rental"
    static let floor_pump_rental = "floor_pump_rental"
    static let mechanic_maintenance = "mechanic_maintenance"
    static let version = "version"
    static let device = "device"
}
