# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'MVVMVideoChat' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    pod 'Alamofire', '4.7.1'
    pod 'SVProgressHUD', '2.2.5'
    pod 'SDWebImage', '4.4.0'
    pod 'ObjectMapper', '3.2.0'
    #pod 'AppRTC'
    #https://github.com/ISBX/apprtc-ios/issues/39
    pod 'libjingle_peerconnection'
    pod 'SocketRocket'
    # Pods for MVVMVideoChat

end
